# Auto-generated by 
if [ -z "$WORKSPACE" ]
then
  export WORKSPACE=/home/Jason/edk2_workspace/edk2_UDK2018/edk2-vUDK2018
fi
if [ -z "$EDK_TOOLS_PATH" ]
then
  export EDK_TOOLS_PATH=/home/Jason/edk2_workspace/edk2_UDK2018/edk2-vUDK2018/BaseTools
fi
if [ -e /home/Jason/edk2_workspace/edk2_UDK2018/edk2-vUDK2018/BaseTools/Bin/Linux-x86_64 ]
then
  if [ ${PATH//home/Jason/edk2_workspace/edk2_UDK2018/edk2-vUDK2018/BaseTools/Bin/Linux-x86_64/} == $PATH ]
  then
    export PATH=/home/Jason/edk2_workspace/edk2_UDK2018/edk2-vUDK2018/BaseTools/Bin/Linux-x86_64:$PATH
  fi
fi
